version: "3.8"

services:
  app: 
    image: node:20.9.0-slim
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    working_dir: /app

volumes:
  node_modules:
